name: pm
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:

  uses-material-design: true

  
  assets:
    - assets/